### ISSUE TITLE
Not working with julia version 1.10.1 on linux systems 

### ISSUE THREAD

**Issue by Brusa99** [JuliaPy/PythonCall.jl#464] opened 2024-02-16 16:08 UTC
**Affects:** JuliaCall 

**Describe the bug**

The new version 1.10.1 release broke the package [juliacall](https://github.com/JuliaPy/PythonCall.jl) on Linux systems.
When importing the package from python a segmentation fault occurs.

How to reproduce:
1. Have julia version 1.10.1 installed in your system (or no version at all, since juliacall installs julia if not present).
2. create a clean conda environment with python (3.9 or superior tested).
3. run `pip install juliacall`
4. open python interactive session and run `import juliacall`

**Note**: this does not happen with version 1.10.0 and on Mac devices.

**Your system**

The bug is present both on manjaro linux (Manjaro Linux x86_64, kernel: 6.1.71-1-MANJARO) and on Ubuntu (Ubuntu 20.04.5 LTS x86_64, kernel 5.15.0-1054-azure).

I raised the issue also on the [julia github](https://github.com/JuliaLang/julia/issues/53363)

**Comment by bjodah** [comment] 2024-02-23 15:08
I experienced this as well, and came here to look if this was reported already, I'm using a Debian (testing-branch) system, using Python `3.11` and Julia `1.10.1`.

**Comment by cjdoris** [comment] 2024-02-29 09:00
Also https://github.com/JuliaLang/julia/issues/53363

**Comment by feefladder** [comment] 2024-02-29 17:34
For people looking for a [fix](https://github.com/AUTODIAL/AutoEIS/issues/95#issuecomment-1967583222):
```
import juliapkg
juliapkg.require_julia("=1.10.0")
juliapkg.resolve()
from juliacall import Main as jl
jl.println("hello world!")
```

**Comment by dpinol** [comment] 2024-03-06 13:23
I can reproduce this error with default python 3.11.4 from  ubuntu 23.04, but it works with pyenv python versions 3.11.6, 3.11.8 & 3.12.2

**Comment by cjdoris** [comment] 2024-03-08 10:27
https://github.com/conda-forge/python-feedstock/issues/222

Looks like pyjulia already experienced some issues with statically linked Python.

**Comment by Brusa99** [comment] 2024-03-08 10:31
I ran the command and got `0`.
I'm running python version 3.10.13 and julia version 1.10.1 and it causes the segfaults.

**Comment by dpinol** [comment] 2024-03-08 11:32
I ran the command from a new virtualenv and got a `1`, but since I didn't personally create the original virtual env (which I had already deleted), I'm not fully sure that I'm reproducing the same configuration

**Comment by feefladder** [comment] 2024-03-08 12:52
I got a `0`. Indeed I switched to PythonCall from PyJulia exactly because PyJulia had problems with statically linked python. This is also an issue over at conda-forge I believe. to further check if python is statically linked, I use `echo $(which python) && ldd $(which python)`:
```
echo $(which python) && ldd $(which python)
/home/user/micromamba/envs/ahf/bin/python
        linux-vdso.so.1 (0x00007fffe4b75000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x000074ff836c9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000074ff836c1000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x000074ff836b9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000074ff835c9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000074ff833b9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x000074ff833b1000)
        /lib64/ld-linux-x86-64.so.2 (0x000074ff83d99000)
```
And we can see that it is statically linked, because there is no link to `libpython.so`

**Comment by LilithHafner** [comment] 2024-03-08 14:52
I have never been able to reproduce this issue and still cannot.
```
x@fedora:~$ python -c "import sysconfig; print(sysconfig.get_config_var('PY_ENABLE_SHARED'))"
1
```
This is consistent with @cjdoris's hypothesis.

**Comment by topolarity** [comment] 2024-03-08 15:10
Unfortunately, the build flags depend on the maintainer (not just the default build flags from Python).

On my system (Ubuntu), the Debian-provided `python3` is OK and the Ubuntu-provided `python3.11` is bad.

However, they are both shared:
```console
$ python3 -c "import sysconfig; print(sysconfig.get_config_var('PY_ENABLE_SHARED'))"
1
$ python3.11 -c "import sysconfig; print(sysconfig.get_config_var('PY_ENABLE_SHARED'))"
1
```

The direct test is to inspect the relocations in the binary:
```console
$ readelf -rW $(which python3.11) | grep environ
0000000000a92620  000006a400000005 R_X86_64_COPY          0000000000a92620 __environ@GLIBC_2.2.5 + 0
$ readelf -rW $(which python3) | grep environ
0000000000562cb8  0000002900000006 R_X86_64_GLOB_DAT      0000000000000000 environ@GLIBC_2.2.5 + 0
```

The `R_X86_64_COPY` relocation causes the segfault

**Comment by topolarity** [comment] 2024-03-08 15:12
Also as a heads up, there's a work-around being landed for 1.10.3: https://github.com/JuliaLang/julia/pull/53643

**Comment by MilesCranmer** [comment] 2024-03-08 15:21
PySR users also experiencing this issue: https://github.com/MilesCranmer/PySR/issues/561

**Comment by cjdoris** [comment] 2024-03-14 19:16
There's a new version of juliacall out which requires julia <=1.10.0, so if you upgrade juliacall things should work again. I'll allow 1.10.3 and 1.11 again later once those are out and shown to work OK.

**Comment by cjdoris** [comment] 2024-05-01 15:05
I confirmed that JuliaCall works with 1.10.3 so I have made a release (JuliaCall 0.9.20) with the updated julia compat entries.

**Closed by cjdoris** 2024-05-01 15:05 UTC
Labels: bug
